name: app_prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0' # Actualizado al SDK más reciente

dependencies:
  flutter:
    sdk: flutter

  # Firebase (versiones estables compatibles con R8)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  # JSON and serialization
  json_annotation: ^4.9.0

  # State Management y DI (Riverpod es ahora el único)
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.2.1

  # UI & Utilidades
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.2 # Actualizado para compatibilidad

  # Notificaciones
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation (útil para modelos y estados inmutables con Riverpod)
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true