name: app_prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0' # Actualizado al SDK más reciente

dependencies:
  flutter:
    sdk: flutter

  # Firebase (actualizado a las últimas versiones estables)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  
  # JSON and serialization
  json_annotation: ^4.9.0

  # State Management y DI (Riverpod es ahora el único)
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^16.2.0

  # UI & Utilidades
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.2 # Actualizado para compatibilidad

  # Notificaciones
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation (útil para modelos y estados inmutables con Riverpod)
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

# Dependency overrides para forzar las versiones más recientes
dependency_overrides:
  # Transitive dependencies
  characters: ^1.4.1
  material_color_utilities: ^0.13.0  
  meta: ^1.17.0
  test_api: ^0.7.7
  
  # Transitive dev_dependencies
  _fe_analyzer_shared: ^88.0.0
  analyzer: ^8.1.1
  dart_style: ^3.1.2