name: app_prueba
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Ampliamos el rango para compatibilidad

dependencies:
  flutter:
    sdk: flutter

  # Firebase (actualizado a las últimas versiones estables)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # State Management y DI (Riverpod es ahora el único)
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.2.0

  # UI & Utilidades
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0 # Actualizado para compatibilidad

  # Notificaciones
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation (útil para modelos y estados inmutables con Riverpod)
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true