// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJu2Ac4xbAe5SGJC49Xt99WJmRTTO0Mpw',
    appId: '1:960030273194:web:eee4879ddd0834a608ead3',
    messagingSenderId: '960030273194',
    projectId: 'agendaapptry',
    authDomain: 'agendaapptry.firebaseapp.com',
    storageBucket: 'agendaapptry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VaWaIq_sV_NxjsCSgiDPITjP95QTPdQ',
    appId: '1:960030273194:android:ee0a2a14932b07ed08ead3',
    messagingSenderId: '960030273194',
    projectId: 'agendaapptry',
    storageBucket: 'agendaapptry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GaWGqVkizXOkO23qAtOpg1Qi0yRL6sc',
    appId: '1:960030273194:ios:ad4b331e75dfbf0a08ead3',
    messagingSenderId: '960030273194',
    projectId: 'agendaapptry',
    storageBucket: 'agendaapptry.firebasestorage.app',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GaWGqVkizXOkO23qAtOpg1Qi0yRL6sc',
    appId: '1:960030273194:ios:ad4b331e75dfbf0a08ead3',
    messagingSenderId: '960030273194',
    projectId: 'agendaapptry',
    storageBucket: 'agendaapptry.firebasestorage.app',
    iosBundleId: 'com.example.appPrueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJu2Ac4xbAe5SGJC49Xt99WJmRTTO0Mpw',
    appId: '1:960030273194:web:1383ea6db4d427a308ead3',
    messagingSenderId: '960030273194',
    projectId: 'agendaapptry',
    authDomain: 'agendaapptry.firebaseapp.com',
    storageBucket: 'agendaapptry.firebasestorage.app',
  );
}
